// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/UnoraApp/be/ent/generated"
	"github.com/UnoraApp/be/internal/auth/handlers"
	"github.com/UnoraApp/be/internal/auth/services"
	"github.com/UnoraApp/be/internal/config"
	"github.com/UnoraApp/be/pkg/storage"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// InitializeContainer creates a fully wired Container
func InitializeContainer(cfg *config.Config, entClient *generated.Client, redisClient *redis.Client, storageClient storage.Client) (*Container, error) {
	authService := services.NewAuthService(entClient, redisClient, cfg)
	authHandler := handlers.NewAuthHandler(authService)
	container := &Container{
		Config:        cfg,
		EntClient:     entClient,
		RedisClient:   redisClient,
		StorageClient: storageClient,
		AuthService:   authService,
		AuthHandler:   authHandler,
	}
	return container, nil
}

// InitializeAuthHandler creates just the auth handler (useful for testing)
func InitializeAuthHandler(entClient *generated.Client, redisClient *redis.Client, cfg *config.Config) *handlers.AuthHandler {
	authService := services.NewAuthService(entClient, redisClient, cfg)
	authHandler := handlers.NewAuthHandler(authService)
	return authHandler
}

// InitializeAuthService creates just the auth service (useful for testing)
func InitializeAuthService(entClient *generated.Client, redisClient *redis.Client, cfg *config.Config) *services.AuthService {
	authService := services.NewAuthService(entClient, redisClient, cfg)
	return authService
}

// wire.go:

// Container holds all initialized dependencies for the application
type Container struct {
	Config        *config.Config
	EntClient     *generated.Client
	RedisClient   *redis.Client
	StorageClient storage.Client

	// Auth
	AuthService *services.AuthService
	AuthHandler *handlers.AuthHandler
}

// AuthSet is the provider set for auth module
var AuthSet = wire.NewSet(services.ProviderSet, handlers.ProviderSet)

// ProviderSet is the complete application provider set
var ProviderSet = wire.NewSet(
	AuthSet,
)
